name: FairyDragmother
favicon: null
layout_spectrum: 0.9638298
typography_spectrum: 0.5234042
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#efd562'
    - '#9372b3'
    - '#090a0b'
    - '#2b262f'
    - '#50435a'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.7
  rhythmicContrast: 0
purpose: []
