name: FairyDragmother
favicon: null
layout_spectrum: 0.9638298
typography_spectrum: 0.5234042
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#eddf43'
    - '#8a63ff'
    - '#090b0c'
    - '#808384'
  brandStrength: 0.8125
  lightness: 0.375
  saturation: 0.7
  rhythmicContrast: 0
purpose: []
